# Generated by Django 2.2.17 on 2021-01-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210112_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
